using System.ComponentModel;
using Octopus.Data.Resources;
using Octopus.Data.Resources.Attributes;
using Octopus.Server.Extensibility.Extensions.Infrastructure.Configuration;

namespace Octopus.Server.Extensibility.IssueTracker.Jira.Configuration
{
    [Description("Configure the Jira Issue Tracker. [Learn more](https://g.octopushq.com/JiraIssueTracker).")]
    public class JiraConfigurationResource : ExtensionConfigurationResource
    {
        public const string JiraBaseUrlDescription = "Enter the base url of your Jira instance. Once set, work item references will render as links.";

        [DisplayName("Jira Base Url")]
        [Description(JiraBaseUrlDescription)]
        [Writeable]
        public string BaseUrl { get; set; }
        
        [DisplayName("Jira Connect App Password")]
        [Description("Set the password for authenticating with the Jira Connect App (generated by the Jira Connect application upon installation in to your Jira instance). Once set deployment data will be sent to Jira.")]
        [Writeable]
        public SensitiveValue Password { get; set; }

        [DisplayName("Octopus Installation Id")]
        [Description("Copy and paste this Id when configuring the Jira Connect application")]
        [ReadOnly(true)]
        [AllowCopyToClipboard]
        public string OctopusInstallationId { get; set; }
        
        [DisplayName("Octopus Server Url")]
        [Description("This Url is required in order to push deployment data to Jira. If it is blank please set it in [Configuration/Nodes](/configuration/nodes)")]
        [ReadOnly(true)]
        public string OctopusServerUrl { get; set; }
    }
}