name: Build, Test, Package and Push

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events and merges/pushes to main
  push:
    branches:
      - '**'
    tags:
      - '**'
  schedule:
    # Daily 5am australian/brisbane time
    - cron: '19 0 * * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  determine-branch:
    runs-on: ubuntu-20.04
    steps:
      - name: OctoVersion setup - standard
        id: set-branch-standard
        if: github.event_name != 'schedule'
        run: echo "::set-output name=branch::${{ github.head_ref || github.ref }}"

      - name: OctoVersion setup - nightly
        id: set-branch-nightly
        if: github.event_name == 'schedule'
        run: echo "::set-output name=branch::nightly"
          echo "::set-output name=patch::${{ github.run_number }}"

    outputs:
        branch: ${{ steps.set-branch-standard.outputs.branch || steps.set-branch-nightly.outputs.branch }}
        patch: ${{ steps.set-branch-standard.outputs.patch || steps.set-branch-nightly.outputs.patch }}

  build:
    runs-on: ubuntu-20.04
    needs: determine-branch
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Nuke Build 🏗
        id: build
        env:
          OCTOVERSION_CurrentBranch: ${{ needs.determine-branch.outputs.branch }}
          OCTOVERSION_Patch: ${{ needs.determine-branch.outputs.patch }}
          JiraIntegration_E2E_BaseUrl: ${{ secrets.JIRA_BASE_URL }}
          JiraIntegration_E2E_Username: ${{ secrets.JIRA_USERNAME }}
          JiraIntegration_E2E_AuthToken: ${{ secrets.JIRA_AUTH_TOKEN }}
        shell: bash
        run: ./build.sh --verbosity verbose

      - name: Push package to feed 🐙
        id: push-feed
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        shell: bash
        env:
          FEED_API_KEY: ${{ secrets.FEED_API_KEY }}
          FEED_SOURCE: ${{ secrets.FEED_SOURCE }}
        run: dotnet nuget push artifacts/**/*.nupkg --api-key "$FEED_API_KEY" --source "$FEED_SOURCE"
